### ISSUE TITLE
QGIS 3 : Crash when calling 'fromPolygon'

### ISSUE THREAD

**Issue by ghost** [jonnyhuck/RFCL-PolygonDivider#10]
First of all, thank you for this plugin, it saved me much time !

I just used it to divide the polygons on a big dataset on QGIS 3. I then encountered the following error :
`'QgsGeometry' object has no attribute 'fromPolygon'`

After a bit of research, I tried to refactor the 2 calls of `fromPolygon` to `fromPolygonXY`, which worked.

I'll submit a PR containing this change.

**Comment by jonnyhuck** [comment]
Hi @Sephtenen,

Thankyou for this - it looks like I had made this change for single Polygons but not for MultiPolygons - good catch! I'll merge it now.
