### ISSUE TITLE
Dividing into large number of polygons throws error.

### ISSUE THREAD

**Issue by pborah88** [jonnyhuck/RFCL-PolygonDivider#14]
Trying to divide the attached polygon into 1000 equal parts gives a float divmod() error. This is a shapefile for Ontario, Canada. Basically any number over 200 throws this error. I'm attaching a screenshot of console error message.
[Ontario boundary.zip](https://github.com/jonnyhuck/RFCL-PolygonDivider/files/6558793/Ontario.boundary.zip)

![image](https://user-images.githubusercontent.com/19488317/119940868-d026ce80-bf5d-11eb-95f6-04b8e9411a63.png)

**Comment by jonnyhuck** [comment]
Thanks for letting me know and providing a test case - I'll take a look and see if I can figure out what's going on

**Comment by jonnyhuck** [comment]
The issue here seems to be that the dataset is not projected - it is in geographic coordinates, which seems to be leading to a maths error as it starts dealing with very small numbers. If you project it (ideally into an Equal Area projection), then it should work fine!

**Comment by EkaterinaEvseeva** [comment]
Using NAD83 / California Albers for California and keep getting the same error: Polygon Division Failed: float divmod()

**Comment by jonnyhuck** [comment]
How strange, would you be able to share the dataset please so I can reproduce/debug?

**Comment by EkaterinaEvseeva** [comment]
Sure. Please find the project in the attachment.
It works for 50 parcels but when I increase the number to 100 I get the error. 
My final goal is to divide California into 1000 parcels.
[Fire.Watch-California Map.qgz.zip](https://github.com/jonnyhuck/RFCL-PolygonDivider/files/8774668/Fire.Watch-California.Map.qgz.zip)

**Comment by jonnyhuck** [comment]
Could you please zip up the shapefile and send it? (the QGIS Project files do not include the data, I would need the data files too). How quickly do you need to get this done?

**Comment by jonnyhuck** [comment]
_(Edited - I divided the wrong polygon with the second image...)_

I just had a go with a polygon I downloaded and projected and it divided into 100 and 1000 no problem using NAD83 / California Albers for California:

![image](https://user-images.githubusercontent.com/8895744/170830504-6ae5d7b0-b20b-4fab-91ef-cc489c8948c7.png)

![Screenshot 2022-05-28 at 16 27 22](https://user-images.githubusercontent.com/8895744/170831956-43dea907-f2aa-4a80-9008-07e9cb882d1f.png)

Is the Shapefile definitely stored in this projection (as opposed to the QGIS project just set to it)?
