### ISSUE TITLE
Float floor division by zero

### ISSUE THREAD

**Issue by robbitt** [jonnyhuck/RFCL-PolygonDivider#17]
Running QGIS 3.22.  If I try and divide any given polygon by number of divisions - I get this error --> "Error: Polygon Division Failed: float floor division by zero"

**Comment by jonnyhuck** [comment]
This sounds like you have a dataset in geographical coordinates (degrees) - you need to project the data before using the tool as it is expecting a planar geometry (I would recommend either an local or an equal area projection). Does that fix it?

There is an outstanding issue to add better error handling for this situation.

**Comment by jonnyhuck** [comment]
I've added a new feature to validate that the dataset is projected this before attempting to divide it
