### ISSUE TITLE
UnboundLocalError: local variable 'maxxi' referenced before assignment

### ISSUE THREAD

**Issue by peruvianwolfie** [jonnyhuck/RFCL-PolygonDivider#2]
I try to use the plugin with QGIS 2.18.11 and got the error "UnboundLocalError: local variable 'maxxi' referenced before assignment"...

**Comment by jonnyhuck** [comment]
How odd - not seen that before - can you send me that dataset that you are splitting please and I'll take a look? Perhaps via a Dropbox link or something?

**Comment by peruvianwolfie** [comment]
Hi Johnny:
Attached to this message is the requested sample dataset.
Regards

JLMM

De: Jonny Huck<mailto:notifications@github.com>
Enviado: viernes, 4 de agosto de 2017 11:40
Para: jonnyhuck/RFCL-PolygonDivider<mailto:RFCL-PolygonDivider@noreply.github.com>
CC: peruvianwolfie<mailto:jlmunozmeza@outlook.com.pe>; Author<mailto:author@noreply.github.com>
Asunto: Re: [jonnyhuck/RFCL-PolygonDivider] UnboundLocalError: local variable 'maxxi' referenced before assignment (#2)


How odd - not seen that before - can you send me that dataset that you are splitting please and I'll take a look? Perhaps via a Dropbox link or something?

**Comment by jonnyhuck** [comment]
Hi @peruvianwolfie , I'm afraid that doesn't seem to have anything attached - I don't think that you can attach files to these issues

**Comment by bendablegears** [comment]
It appears to be happening for any polygon containing a negative latitude or longitude point. (QGIS 2.18.13), I was able to reproduce the issue with a simple quad.

[polygon_divider_test.zip](https://github.com/jonnyhuck/RFCL-PolygonDivider/files/1387580/polygon_divider_test.zip)

**Comment by jonnyhuck** [comment]
Thanks for your feedback on this - I think that this relates to a pull request that I received overnight whereby the script does not work for negative coordinates - I will review the pull request today all being well, but it looks like that will solve the issue for you.

Thanks again Jonny

**Comment by jonnyhuck** [comment]
Thanks for the feedback and the pull request, that's a great catch!
