### ISSUE TITLE
python api 

### ISSUE THREAD

**Issue by xiuweihan** [jonnyhuck/RFCL-PolygonDivider#22]
hello,

Can this project provide python api, I hope to use python to call the function directly，Thanks.

**Comment by jonnyhuck** [comment]
This would certainly be possible - are you thinking of an implementation that still relys on pyqgis, or something built on a more easily installed 'standalone' (e.g., fiona)?

**Comment by xiuweihan** [comment]
> This would certainly be possible - are you thinking of an implementation that still relys on pyqgis, or something built on a more easily installed 'standalone' (e.g., fiona)?


Thanks for the reply, I was thinking of "a more easily installed 'standalone'", eg, pip install polygon_divider.

Of course, if publishing the pypi package is time-consuming, can you provide a function entry, you can pass in parameters(e.g., polygon coordinates, number of groups, etc), and get the result(coordinates of sub-polygons) after running.The example is as follows:


def polygon_divider(polygon, number, *args, **kwargs):
	"""
	:param polygon: polygon coordinates, eg: [[0,0], [10,0], [10, 20], [0, 20]]
	:param number: number of groups, eg:N
	"""
	# TODO:Return N subpolygon coordinates
	
	return sub_polygon

**Comment by xiuweihan** [comment]
> This would certainly be possible - are you thinking of an implementation that still relys on pyqgis, or something built on a more easily installed 'standalone' (e.g., fiona)?

Thanks for the reply, I was thinking of "a more easily installed 'standalone'", eg, pip install polygon_divider.

Of course, if publishing the pypi package is time-consuming, can you provide a function entry, you can pass in parameters(e.g., polygon coordinates, number of groups, etc), and get the result(coordinates of sub-polygons) after running.The example is as follows:

def polygon_divider(polygon, target_area, *args, **kwargs):
"""
:param polygon: polygon coordinates, eg: [[0,0], [10,0], [10, 20], [0, 20]]
:param number: target_area, eg: N
"""
