### ISSUE TITLE
type object 'QgsMessageLog' has no attribute 'CRITICAL'

### ISSUE THREAD

**Issue by jameslamping** [jonnyhuck/RFCL-PolygonDivider#23]
I am running into two issues. One is that if the whole process runs to 100% I get a shapefile that is somehow not readable. It ends up being a large shapefile but has no extent when I load it. The second is that most of the time I get an error of "type object 'QgsMessageLog' has no attribute 'CRITICAL'" and I am not able to divide my polygon. I can provide the polygon to you via email if needed.

**Comment by jonnyhuck** [comment]
Hi James,

How strange, can you please send the polygon that you are trying to divide (along with the settings that you are using, QGIS version and Operating system) to jonathan.huck@manchester.ac.uk and I'll take a look?

**Comment by jameslamping** [comment]
For others who are potentially interested in this issue I have sent Jonny an email with the details. 

Jonny, I wanted to follow up with a typo I found in my email. I am trying to divide the polygons into 40 hectare areas, not 4 hectare areas. Thanks again for looking into this!

**Comment by jonnyhuck** [comment]
No problem, the error message that you were getting is related to a minor bug in the code (a hangover from the QGIS2 version). The snag is that this bug is in the error logging - the underlying problem is that it is failing to divide the polygon, I just need to figure out why!

**Comment by jameslamping** [comment]
Thanks for looking into this!

**Comment by HansBrandes** [comment]
Hy Jonny - did you solve the problem and how?? The tool runns perfekt on a layer with one right-angled polygone. (Thanks for that). But I have a Layer with with 92 polygons withvery different shapes and I get now the message about `Critical` - I´m using QGIS 3.30.
Thanks

**Comment by jonnyhuck** [comment]
Hi Hans,

The "Critical" message is an error that is caused when another error occurs - normally when you try to divide a polygon that is not projected - what is the CRS of your layer?

**Comment by HansBrandes** [comment]
Thanks for your fast replay - EPSG code is 25832-ETRS89 / UTM zone 32N

**Comment by jonnyhuck** [comment]
Ok, would you be willing to send me a copy of the dataset to github.magenta278@passmail.net so I can investigate please?

**Comment by jonnyhuck** [comment]
OK, I have fixed the bug that this issue refers to (the Critical message one) and opened a new issue for the unsplittable layer ( #26 )
