### ISSUE TITLE
is there any version for QGIS 3.x??

### ISSUE THREAD

**Issue by JCCabreraMX** [jonnyhuck/RFCL-PolygonDivider#4]
Is there any version for QGIS 3.x?? It will be so on future??

**Comment by jonnyhuck** [comment]
Not just yet - but hopefully yes there will be in the near future.

**Comment by nickislander** [comment]
Much appreciated! This plugin is important for a specific workflow of mine.

**Comment by kapildevadk** [comment]
I also made 90% review works to port to Qgis 3.x version.

**Comment by jonnyhuck** [comment]
I have made a working version in QGIS3 - I'll get it pushed up here ASAP - it is slightly different (with a few more options though notably missing the PostGIS link)

**Comment by jonnyhuck** [comment]
I have just pushed the QGIS version to the repo, so it should be available on in the QGIS Plugin manager shortly. Thankyou very much for your interest and efforts

**Comment by kapildevadk** [comment]
Great, Dear Jonny Huck Sir.
