### ISSUE TITLE
Output to PostGIS failing due to multipolygons

### ISSUE THREAD

**Issue by MikeLush** [jonnyhuck/RFCL-PolygonDivider#7]
The plugin occassionally produces multipolygons. Whilst I don't think this is intended, at the moment it can lead to an entire batch failing to write out to PostGIS, inserting the following message in the log (I've generalised the command text):

> Feature could not be written to the output table. Reverted latest batch of PostGIS changes. Geometry type (MultiPolygon) does not match column type (Polygon)
> Command text: INSERT INTO [table] (geom,existing_fields],poly_id,unique_id,area,pointx,pointy) VALUES(ST_GeomFromText('MultiPolygon ((([coords])))', [srid]),[attributes])

A solution to this would seem to be to specify a generic GEOMETRY type when creating the output table, rather than the POLYGON type currently being used. This would allow output of the expected polygons, but would also handle multipolygons if they are produced without losing all the singlepart polygons in the same batch.

For information, multipolygons seem to be produced where the boundary of the input polygon contains the same vertex twice, as in the image below.

![image](https://user-images.githubusercontent.com/25057691/61042620-79956300-a3cc-11e9-9215-a7d3afc178e9.png)

**Comment by MikeLush** [comment]
NB: this relates to #5.

It's also quite easy to do*, but may not be the best solution. Having discussed with @ClaireLush, it seems likely that the division process can create a multipolygon that is not handled in the original code. The correct solution would be to find and handle the multipolygon output, rather than allow any geometry to be written to PostGIS.

\* Change line 195 of polygondivider.py to:

``` python
sqlCmd.append('geom geometry(Geometry,{0})'.format(self.crs))
```

**Comment by jonnyhuck** [comment]
How odd - thankyou for the research into why this is happening as well. An interim solution could be to have a look at using functions like `ST_Dump` in PostGIS - but yes, we should try and put a fix in for this (I suspect that it arising from how QGIS handles that situation, but there should be a workaround)

**Comment by MikeLush** [comment]
It's doesn't matter so much to us anyway, as our processes deal with any multipolygons using `ST_Dump` as you suggest. However, in order to do this we have to be able to get the data into PostGIS, which currently requires a relaxation of the restriction on geometry types in the output table.

I'm not sure it's such an issue with shapefiles. My admittedly limited understanding of what goes on under the bonnet of the ESRI shapefile format is that polygons and multipolyons are all handled by the POLYGON(M/Z) shape types, which means if multipolygons are produced as an output by this tool they will save to shapefile quite happily.

**Comment by jonnyhuck** [comment]
Closed as QGIS2 version not commonly used any longer
